"""Generates the forwarding half of a proxy nvcuda.dll.

DLSS resolves its CUDA entry points from the module by name, so the only way to
see the arguments and results of that conversation is to sit between it and the
driver. Every export we do not care about is forwarded straight to the real
ZLUDA build, which the loader resolves at bind time for no runtime cost.

The forwarders are emitted as linker pragmas rather than into a .def file: MSVC
reads `name=dll.name` in a .def as an alias to a local symbol and fails to link,
while the pragma form is unambiguous.

Usage: gen_cuda_proxy.py <exports.txt> <out.h>
"""
import sys

# The resource identity conversation. EvaluateFeature fails when the snippet
# asks CUDA what a handle is and gets no answer, so these are the calls whose
# arguments and results decide the outcome. Implemented in nvcuda_proxy.cpp.
LOGGED = {
    # The resource identity conversation.
    "cuTexObjectCreate",
    "cuTexObjectGetResourceDesc",
    "cuTexObjectDestroy",
    "cuSurfObjectCreate",
    "cuSurfObjectGetResourceDesc",
    "cuSurfObjectDestroy",
    "cuArrayGetDescriptor_v2",
    "cuArrayCreate_v2",
    "cuMipmappedArrayGetLevel",
    # The dispatch path: where the evaluation now stops.
    "cuModuleLoadData",
    "cuModuleGetFunction",
    "cuFuncSetAttribute",
    "cuLaunchKernel",
    "cuMemAlloc_v2",
    "cuMemcpyHtoDAsync_v2",
    "cuDeviceGetAttribute",
    # Without these the rest is blind: the snippet does not resolve its entry
    # points with GetProcAddress, it asks the driver for them, and the pointers
    # it gets back skip every wrapper. Intercepting the lookup is what puts the
    # proxy back in the path.
    "cuGetProcAddress",
    "cuGetProcAddress_v2",
}

# Not forwardable: the loader would bind our DllMain to ZLUDA's, and the delay
# load hooks are data exports of the C runtime, not functions.
SKIP = {"DllMain", "__pfnDliFailureHook2", "__pfnDliNotifyHook2"}


def main():
    names = [n.strip() for n in open(sys.argv[1]) if n.strip()]
    out = [
        "// Generated by tools/gen_cuda_proxy.py -- do not edit.",
        "#pragma once",
        "",
    ]
    forwarded = 0
    for n in names:
        if n in SKIP or n in LOGGED:
            continue
        out.append(f'#pragma comment(linker, "/export:{n}=zluda_real.{n}")')
        forwarded += 1
    open(sys.argv[2], "w").write("\n".join(out) + "\n")
    print(f"{forwarded} exports forwarded, {len(LOGGED)} implemented and logged")


main()
