#!/usr/bin/env python3
"""Generates gate_forwards.h: every ZLUDA export the gate does not implement,
forwarded straight to zluda_real.dll.

The loader binds a forwarder at load time, so the thousands of calls the
network makes that the gate has no interest in cost nothing. For MSVC the
forwarders are linker pragmas rather than a .def file: MSVC reads `name=dll.name`
in a .def as an alias to a local symbol and fails to link, while the pragma is
unambiguous. GNU ld has no such pragma and reads the same line in a .def as a
forwarder, so a third argument also writes a .def (mingw links it, MSVC is not given it).

The export list is zluda_exports.txt. Regenerate it when ZLUDA gains exports,
from the DLL itself:  dumpbin /exports zluda_real.dll

Usage: gen_forwards.py [zluda_exports.txt] [gate_forwards.h] [gate.def]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Implemented in gate.cpp. The snippet resolves its entry points through
# cuGetProcAddress, not through the export table, so the lookup has to be
# intercepted for the launch wrapper to be reached at all.
IMPLEMENTED = {
    "cuGetProcAddress",
    "cuGetProcAddress_v2",
    "cuModuleGetFunction",
    "cuLaunchKernel",
}

# Not forwardable: the loader would bind our DllMain to ZLUDA's, and the delay
# load hooks are data exports of the C runtime, not functions.
SKIP = {"DllMain", "__pfnDliFailureHook2", "__pfnDliNotifyHook2"}


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "zluda_exports.txt")
    target = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "gate_forwards.h")
    names = [n.strip() for n in open(source) if n.strip()]
    out = ["// Generated by gen_forwards.py from zluda_exports.txt -- do not edit.", "#pragma once", ""]
    forwarded = 0
    for n in names:
        if n in SKIP or n in IMPLEMENTED:
            continue
        out.append('#pragma comment(linker, "/export:%s=zluda_real.%s")' % (n, n))
        forwarded += 1
    open(target, "w", newline="\n").write("\n".join(out) + "\n")
    if len(sys.argv) > 3:
        lines = ["LIBRARY nvcuda", "EXPORTS"]
        lines += ["    %s = zluda_real.%s" % (n, n) for n in names if n not in SKIP and n not in IMPLEMENTED]
        open(sys.argv[3], "w", newline="\n").write("\n".join(lines) + "\n")
    print("%d exports forwarded, %d implemented" % (forwarded, len(IMPLEMENTED)))


if __name__ == "__main__":
    main()
