#!/usr/bin/env python3
"""Generates the forwarders that carry HIP calls from Windows code to ROCm.

Under Wine or Proton the network runs on ZLUDA, a Windows DLL that calls the
HIP runtime through amdhip64_7.dll. On Linux that runtime is libamdhip64.so, a
native library. Two small pieces connect them:

  * the trampoline, a Windows DLL named amdhip64_7.dll that exports every HIP
    function ZLUDA uses and does nothing but pack the call into a structure and
    hand it to the native side (trampoline/);
  * the bridge, a native library that unpacks the structure and calls the real
    function (bridge/).

Every function is a call with integers and pointers only, so the call is one
structure: each argument in a 64-bit slot, and a 32-bit slot for the result.
The two processes' memory is one address space (Wine runs both sides in one
process), so a pointer passed is a pointer that works on the other side.

This script reads the list of functions (hip_functions.txt) and their types
from ZLUDA's bindings of the HIP headers, and writes the three generated files.
A function whose type it cannot reduce to an integer or a pointer stops it:
that is the one that needs writing by hand.

  python linux/gen_forwarders.py [--hip-rs path/to/hip_runtime-sys/src/lib.rs]
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Functions that are written by hand in bridge/core.c, because what they pass
# is not the same on the two systems.
SPECIAL = {"hipImportExternalMemory"}

POINTER_SIZED = {"usize", "isize", "u64", "i64", "::core::ffi::c_ulonglong", "::core::ffi::c_longlong"}
# A short or a byte travels in a 32-bit slot: the callee reads the low part of
# the register, which is all an integer argument of that size occupies.
INT_SIZED = {"::core::ffi::c_int", "::core::ffi::c_uint", "i32", "u32", "::core::ffi::c_ushort",
             "::core::ffi::c_short", "::core::ffi::c_uchar", "::core::ffi::c_schar", "::core::ffi::c_char",
             "u16", "i16", "u8", "i8"}


class Types:
    """What each name in the bindings comes down to: 'P' (64 bits) or 'I' (32)."""

    def __init__(self, source):
        self.alias = {}
        for m in re.finditer(r"^pub type (\w+) = ([^;]+);", source, re.M):
            self.alias[m.group(1)] = m.group(2).strip()
        for m in re.finditer(r"^pub struct (\w+)\(pub ([^)]+)\);", source, re.M):
            self.alias.setdefault(m.group(1), m.group(2).strip())

    def classify(self, text, seen=()):
        text = text.strip()
        if text.startswith("*") or text.startswith("::core::option::Option<unsafe"):
            return "P"
        if text in POINTER_SIZED:
            return "P"
        if text in INT_SIZED:
            return "I"
        if text in self.alias and text not in seen:
            return self.classify(self.alias[text], seen + (text,))
        raise ValueError("cannot reduce the type %r to an integer or a pointer" % text)


def read_functions(source, names, types):
    functions = []
    for name in names:
        m = re.search(r"pub fn %s\(([^)]*)\)\s*(?:->\s*([^;]+))?;" % re.escape(name), source)
        if not m:
            raise ValueError("%s is not declared in the bindings" % name)
        params = []
        text = m.group(1).strip()
        if text:
            for part in re.split(r",\s*(?=\w+\s*:)", text.rstrip(",")):
                pname, ptype = part.split(":", 1)
                params.append((pname.strip(), types.classify(ptype)))
        returns = (m.group(2) or "").strip()
        if returns not in ("hipError_t",):
            raise ValueError("%s returns %r, not hipError_t" % (name, returns))
        functions.append((name, params))
    return functions


C_TYPE = {"P": "uint64_t", "I": "int32_t"}
BANNER = "/* Generated by linux/gen_forwarders.py from the HIP bindings; do not edit. */\n"


def write_header(path, functions):
    out = [BANNER, "#pragma once\n#include <stdint.h>\n\n"]
    out.append("enum hip_forwarder {\n")
    for name, _ in functions:
        out.append("    HIPF_%s,\n" % name)
    out.append("    HIPF_COUNT\n};\n\n")
    out.append("#define HIPF_NAMES \\\n")
    out.append(", \\\n".join('    "%s"' % name for name, _ in functions) + "\n\n")
    for name, params in functions:
        out.append("struct args_%s {\n" % name)
        for i in range(len(params)):
            out.append("    uint64_t a%d;\n" % i)
        out.append("    int32_t ret;\n};\n")
    open(path, "w", newline="\n").write("".join(out))


def pack(i, kind):
    return "(uint64_t)(uint32_t)a%d" % i if kind == "I" else "a%d" % i


def write_exports(path, functions):
    out = [BANNER, '#include "../core.h"\n#include "../../generated/hip_forwarders.h"\n\n']
    for name, params in functions:
        decl = ", ".join("%s a%d" % (C_TYPE[k], i) for i, (_, k) in enumerate(params)) or "void"
        out.append("HIPAPI int32_t %s(%s) {\n" % (name, decl))
        init = ", ".join(pack(i, k) for i, (_, k) in enumerate(params))
        out.append("    struct args_%s a = { %s%s0 };\n" % (name, init, ", " if init else ""))
        out.append("    if (!dlssnr_call(HIPF_%s, &a)) return DLSSNR_HIP_NOT_INITIALIZED;\n" % name)
        out.append("    return a.ret;\n}\n\n")
    open(path, "w", newline="\n").write("".join(out))


def write_thunks(path, functions):
    out = [BANNER, '#include "../core.h"\n#include "../../generated/hip_forwarders.h"\n\n']
    for name, params in functions:
        if name in SPECIAL:
            out.append("int32_t thunk_special_%s(void *args);\n" % name)
    out.append("\n")
    for name, params in functions:
        if name in SPECIAL:
            continue
        types = ", ".join(C_TYPE[k] for _, k in params) or "void"
        call = ", ".join(("(int32_t)a->a%d" if k == "I" else "a->a%d") % i for i, (_, k) in enumerate(params))
        out.append("static int32_t thunk_%s(void *args) {\n" % name)
        out.append("    struct args_%s *a = (struct args_%s *)args;\n" % (name, name))
        out.append("    dlssnr_trace_args(HIPF_%s, args);\n" % name)
        out.append("    void *fn = dlssnr_real(HIPF_%s);\n" % name)
        out.append("    a->ret = fn ? ((int32_t (*)(%s))fn)(%s) : DLSSNR_HIP_NOT_SUPPORTED;\n" % (types, call))
        out.append("    return 0;\n}\n\n")
    out.append("/* The native side's table: what the Windows side's handle points at. */\n")
    out.append("const dlssnr_entry dlssnr_funcs[HIPF_COUNT] = {\n")
    for name, _ in functions:
        out.append("    %s,\n" % (("thunk_special_" if name in SPECIAL else "thunk_") + name))
    out.append("};\n")
    open(path, "w", newline="\n").write("".join(out))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--hip-rs", default=os.path.join(ROOT, "third_party", "ZLUDA", "ext", "hip_runtime-sys", "src", "lib.rs"))
    arguments = ap.parse_args()
    source = open(arguments.hip_rs, encoding="utf-8").read()
    names = [n.strip() for n in open(os.path.join(HERE, "hip_functions.txt"), encoding="utf-8")
             if n.strip() and not n.startswith("#")]
    try:
        functions = read_functions(source, names, Types(source))
    except ValueError as error:
        sys.exit("gen_forwarders: %s" % error)
    os.makedirs(os.path.join(HERE, "generated"), exist_ok=True)
    write_header(os.path.join(HERE, "generated", "hip_forwarders.h"), functions)
    os.makedirs(os.path.join(HERE, "trampoline", "generated"), exist_ok=True)
    write_exports(os.path.join(HERE, "trampoline", "generated", "exports.c"), functions)
    os.makedirs(os.path.join(HERE, "bridge", "generated"), exist_ok=True)
    write_thunks(os.path.join(HERE, "bridge", "generated", "thunks.c"), functions)
    print("%d functions, %d of them by hand" % (len(functions), sum(1 for n, _ in functions if n in SPECIAL)))


if __name__ == "__main__":
    main()
