// Compiles the compute shaders of core/shaders.h with Microsoft's compiler and
// writes the bytecode as core/shaders_dxbc.h.
//
// Why: the runtime compiles them when it starts, and that compiler is the one in
// the system. Under Wine it is vkd3d's, which cannot build them
// (RWByteAddressBuffer.Load is not defined there). core/passes.cpp falls back on
// this bytecode when compiling fails, so a prefix does not need Microsoft's
// d3dcompiler_47.dll. Run it again whenever shaders.h changes: the header
// carries a hash of the source, and a stale one is not used.
//
//   gen_dxbc.exe <path to d3dcompiler_47.dll> <output header>
//
// It can run under Wine with Microsoft's DLL given by its path.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3dcompiler.h>

#include <cstdio>
#include <cstdint>

#include "../core/shaders.h"

using namespace dlss5nr;

static const char *const kEntry[] = {"exposure_main", "capture_main", "refresh_main", "soften_main", "track_main",
                                     "compose_main"};

int wmain(int argc, wchar_t **argv) {
    if (argc != 3) {
        fprintf(stderr, "gen_dxbc <d3dcompiler_47.dll> <output header>\n");
        return 2;
    }
    HMODULE lib = LoadLibraryW(argv[1]);
    auto compile = lib ? (pD3DCompile)GetProcAddress(lib, "D3DCompile") : nullptr;
    if (!compile) {
        fprintf(stderr, "no D3DCompile in %ls\n", argv[1]);
        return 1;
    }
    FILE *out = _wfopen(argv[2], L"wb");
    if (!out) return 1;
    fprintf(out, "// Generated by tools/gen_dxbc.cpp from shaders.h; do not edit.\n");
    fprintf(out, "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n");
    fprintf(out, "namespace dlss5nr {\n\n");
    fprintf(out, "// shader_hash(kShaderSource) when this was made.\n");
    fprintf(out, "inline constexpr uint64_t kDxbcSourceHash = 0x%016llxull;\n\n", (unsigned long long)shader_hash(kShaderSource));
    for (int i = 0; i < 6; ++i) {
        ID3DBlob *code = nullptr, *log = nullptr;
        if (FAILED(compile(kShaderSource, sizeof kShaderSource - 1, "dlss5nr", nullptr, nullptr, kEntry[i], "cs_5_1",
                           D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &log))) {
            fprintf(stderr, "%s: %s\n", kEntry[i], log ? (const char *)log->GetBufferPointer() : "?");
            return 1;
        }
        const unsigned char *bytes = (const unsigned char *)code->GetBufferPointer();
        const size_t size = code->GetBufferSize();
        fprintf(out, "inline constexpr unsigned char kDxbc_%s[] = {", kEntry[i]);
        for (size_t k = 0; k < size; ++k) fprintf(out, "%s%u,", k % 24 ? "" : "\n    ", bytes[k]);
        fprintf(out, "\n};\n\n");
        fprintf(stderr, "%s: %zu bytes\n", kEntry[i], size);
    }
    fprintf(out, "struct Dxbc {\n    const unsigned char *data;\n    size_t size;\n};\n\n");
    fprintf(out, "inline constexpr Dxbc kDxbc[] = {\n");
    for (int i = 0; i < 6; ++i) fprintf(out, "    {kDxbc_%s, sizeof kDxbc_%s},\n", kEntry[i], kEntry[i]);
    fprintf(out, "};\n\n} // namespace dlss5nr\n");
    fclose(out);
    return 0;
}
